//
// AgentLanguage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum AgentLanguage: String, Codable, CaseIterable {
    case en = "en"
    case fr = "fr"
    case ja = "ja"
    case es = "es"
}
