//
// AgentPagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AgentPagination: Codable, JSONEncodable, Hashable {

    /** The list of agents returned. */
    public var items: [AgentResponse]
    /** The current index of the page selected. */
    public var index: Int
    /** Whether there is a next page. */
    public var hasNext: Bool

    public init(items: [AgentResponse], index: Int, hasNext: Bool) {
        self.items = items
        self.index = index
        self.hasNext = hasNext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case index
        case hasNext = "has_next"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(index, forKey: .index)
        try container.encode(hasNext, forKey: .hasNext)
    }
}

