//
// AgentCost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AgentCost: Codable, JSONEncodable, Hashable {

    /** The provider of the agent. */
    public var provider: AgentProvider?
    /** The cost for the agent compute usage, discount included. */
    public var cost: Double
    /** The number of minutes used for the agent. */
    public var seconds: Double
    /** The discount percentage of agent cost. */
    public var discount: Int

    public init(provider: AgentProvider? = nil, cost: Double, seconds: Double, discount: Int) {
        self.provider = provider
        self.cost = cost
        self.seconds = seconds
        self.discount = discount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case cost
        case seconds
        case discount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encode(cost, forKey: .cost)
        try container.encode(seconds, forKey: .seconds)
        try container.encode(discount, forKey: .discount)
    }
}

