//
// Agent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Agent: Codable, JSONEncodable, Hashable {

    /** The name of the agent */
    public var name: AnyCodable?
    /** The initial message of the agent */
    public var initialMessage: AnyCodable?
    /** The prompt of the agent */
    public var prompt: AnyCodable?
    /** DO NOT USE! Deprecated! */
    public var language: AgentLanguage?
    public var languageModel: OpenAI?
    public var voice: Voice?
    public var transcriber: Transcriber?
    /** The maximum call duration in seconds. If null, the call can be of any duration. The default value is 10 min. */
    public var maxCallDuration: AnyCodable?
    /** The webhooks of the agent */
    public var webhooks: AnyCodable?
    /** The id of the agent */
    public var id: AnyCodable?
    /** The uri of the agent */
    public var uri: AnyCodable?
    /** The id of the owner of the agent */
    public var accountId: AnyCodable?
    /** The date and time the agent was created */
    public var createdAt: AnyCodable?
    /** The date and time the agent was last updated */
    public var updatedAt: AnyCodable?

    public init(name: AnyCodable?, initialMessage: AnyCodable?, prompt: AnyCodable?, language: AgentLanguage? = nil, languageModel: OpenAI? = nil, voice: Voice? = nil, transcriber: Transcriber? = nil, maxCallDuration: AnyCodable? = nil, webhooks: AnyCodable? = nil, id: AnyCodable?, uri: AnyCodable?, accountId: AnyCodable?, createdAt: AnyCodable?, updatedAt: AnyCodable?) {
        self.name = name
        self.initialMessage = initialMessage
        self.prompt = prompt
        self.language = language
        self.languageModel = languageModel
        self.voice = voice
        self.transcriber = transcriber
        self.maxCallDuration = maxCallDuration
        self.webhooks = webhooks
        self.id = id
        self.uri = uri
        self.accountId = accountId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case initialMessage = "initial_message"
        case prompt
        case language
        case languageModel = "language_model"
        case voice
        case transcriber
        case maxCallDuration = "max_call_duration"
        case webhooks
        case id
        case uri
        case accountId = "account_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(initialMessage, forKey: .initialMessage)
        try container.encode(prompt, forKey: .prompt)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(languageModel, forKey: .languageModel)
        try container.encodeIfPresent(voice, forKey: .voice)
        try container.encodeIfPresent(transcriber, forKey: .transcriber)
        try container.encodeIfPresent(maxCallDuration, forKey: .maxCallDuration)
        try container.encodeIfPresent(webhooks, forKey: .webhooks)
        try container.encode(id, forKey: .id)
        try container.encode(uri, forKey: .uri)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

