//
// AzureLanguages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum AzureLanguages: String, Codable, CaseIterable {
    case enUs = "en-US"
    case frFr = "fr-FR"
    case esEs = "es-ES"
    case deDe = "de-DE"
    case itIt = "it-IT"
    case nlNl = "nl-NL"
    case ptBr = "pt-BR"
    case ruRu = "ru-RU"
    case jaJp = "ja-JP"
    case zhCn = "zh-CN"
    case koKr = "ko-KR"
    case arSa = "ar-SA"
    case hiIn = "hi-IN"
    case idId = "id-ID"
    case trTr = "tr-TR"
    case ukUa = "uk-UA"
    case plPl = "pl-PL"
    case svSe = "sv-SE"
    case daDk = "da-DK"
    case nbNo = "nb-NO"
    case fiFi = "fi-FI"
    case viVn = "vi-VN"
    case thTh = "th-TH"
    case csCz = "cs-CZ"
}
