//
// AzureModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum AzureModel: String, Codable, CaseIterable {
    case steffanNeural = "en-US-SteffanNeural"
    case jennyNeural = "en-US-JennyNeural"
    case andrewNeural = "en-US-AndrewNeural"
    case emmaNeural = "en-US-EmmaNeural"
    case avaNeural = "en-US-AvaNeural"
    case brianNeural = "en-US-BrianNeural"
    case avaMultilingualNeural = "en-US-AvaMultilingualNeural"
    case jennyMultilingualNeural = "en-US-JennyMultilingualNeural"
    case ryanMultilingualNeural = "en-US-RyanMultilingualNeural"
    case andrewMultilingualNeural = "en-US-AndrewMultilingualNeural"
    case brianMultilingualNeural = "en-US-BrianMultilingualNeural"
    case emmaMultilingualNeural = "en-US-EmmaMultilingualNeural"
    case alloyMultilingualNeural = "en-US-AlloyMultilingualNeural"
    case echoMultilingualNeural = "en-US-EchoMultilingualNeural"
    case fableMultilingualNeural = "en-US-FableMultilingualNeural"
    case novaMultilingualNeural = "en-US-NovaMultilingualNeural"
    case onyxMultilingualNeural = "en-US-OnyxMultilingualNeural"
    case shimmerMultilingualNeural = "en-US-ShimmerMultilingualNeural"
}
