//
// BuyPhoneNumber.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BuyPhoneNumber: Codable, JSONEncodable, Hashable {

    public enum Provider: String, Codable, CaseIterable {
        case twilio = "twilio"
    }
    /** The telephony provider. */
    public var provider: Provider? = .twilio
    /** The phone number to buy. */
    public var phoneNumber: String

    public init(provider: Provider? = .twilio, phoneNumber: String) {
        self.provider = provider
        self.phoneNumber = phoneNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case phoneNumber = "phone_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encode(phoneNumber, forKey: .phoneNumber)
    }
}

