//
// CallType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum CallType: String, Codable, CaseIterable {
    case inboundPhoneCall = "inbound_phone_call"
    case outboundPhoneCall = "outbound_phone_call"
}
