//
// CallStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum CallStatus: String, Codable, CaseIterable {
    case live = "live"
    case ended = "ended"
}
