//
// ChatGPT.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum ChatGPT: String, Codable, CaseIterable {
    case _41106preview = "gpt-4-1106-preview"
    case _35turbo1106 = "gpt-3.5-turbo-1106"
}
