//
// CreateCall.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCall: Codable, JSONEncodable, Hashable {

    public var toNumber: String
    public var fromNumber: String
    public var agent: Agent

    public init(toNumber: String, fromNumber: String, agent: Agent) {
        self.toNumber = toNumber
        self.fromNumber = fromNumber
        self.agent = agent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case toNumber = "to_number"
        case fromNumber = "from_number"
        case agent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(toNumber, forKey: .toNumber)
        try container.encode(fromNumber, forKey: .fromNumber)
        try container.encode(agent, forKey: .agent)
    }
}

