//
// Currency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum Currency: String, Codable, CaseIterable {
    case usd = "usd"
}
