//
// DeepgramModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum DeepgramModel: String, Codable, CaseIterable {
    case _2 = "nova-2"
    case _2general = "nova-2-general"
    case _2meeting = "nova-2-meeting"
    case _2phonecall = "nova-2-phonecall"
    case _2finance = "nova-2-finance"
    case _2voicemail = "nova-2-voicemail"
    case _2medical = "nova-2-medical"
    case _2drivethru = "nova-2-drivethru"
    case _2automotive = "nova-2-automotive"
    case _2conversationalai = "nova-2-conversationalai"
}
