//
// DeepgramLanguages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum DeepgramLanguages: String, Codable, CaseIterable {
    case en = "en"
    case fr = "fr"
    case es = "es"
    case de = "de"
    case it = "it"
    case nl = "nl"
    case pt = "pt"
    case ru = "ru"
    case ja = "ja"
    case cs = "cs"
    case da = "da"
    case el = "el"
    case hi = "hi"
    case id = "id"
    case ko = "ko"
    case no = "no"
    case pl = "pl"
    case sv = "sv"
    case tr = "tr"
    case uk = "uk"
}
