//
// ElevenLabsModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum ElevenLabsModel: String, Codable, CaseIterable {
    case _21m00Tcm4TlvDq8ikWAM = "21m00Tcm4TlvDq8ikWAM"
    case _5q0t7uMcjvnagumLfvZi = "5Q0t7uMcjvnagumLfvZi"
    case _29vD33N1CtxCmqQRPOHJ = "29vD33N1CtxCmqQRPOHJ"
    case _2eiwWnXFnvU5JabPnv8n = "2EiwWnXFnvU5JabPnv8n"
    case cyw3kz02hs0563khs1fj = "CYw3kZ02Hs0563khs1Fj"
    case d38z5RcWu1voky8WS1ja = "D38z5RcWu1voky8WS1ja"
    case exavitqu4vr4xnsdxmal = "EXAVITQu4vr4xnSDxMaL"
}
