//
// EventVariableName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum EventVariableName: String, Codable, CaseIterable {
    case callDuration = "call_duration"
    case silenceDuration = "silence_duration"
}
