//
// EventName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum EventName: String, Codable, CaseIterable {
    case openaiFunctionCallTriggered = "openai_function_call_triggered"
    case callStarted = "call_started"
    case message = "message"
    case callEnded = "call_ended"
}
