//
// MessageRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum MessageRole: String, Codable, CaseIterable {
    case agent = "agent"
    case human = "human"
}
