//
// Message.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Message: Codable, JSONEncodable, Hashable {

    /** The role of the message. */
    public var role: MessageRole
    /** The content of the message. */
    public var content: String

    public init(role: MessageRole, content: String) {
        self.role = role
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
        try container.encode(content, forKey: .content)
    }
}

