//
// MethodEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum MethodEnum: String, Codable, CaseIterable {
    case _get = "GET"
    case post = "POST"
}
