//
// OpenAIFunctionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum OpenAIFunctionType: String, Codable, CaseIterable {
    case object = "object"
}
