//
// PhoneNumberToBuy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PhoneNumberToBuy: Codable, JSONEncodable, Hashable {

    public enum Provider: String, Codable, CaseIterable {
        case twilio = "twilio"
    }
    /** The telephony provider. */
    public var provider: Provider? = .twilio
    /** The phone number. */
    public var phoneNumber: String
    /** The postal code of the phone number. */
    public var postalCode: String?
    /** The iso country code of the phone number. */
    public var isoCountry: String?

    public init(provider: Provider? = .twilio, phoneNumber: String, postalCode: String? = nil, isoCountry: String? = nil) {
        self.provider = provider
        self.phoneNumber = phoneNumber
        self.postalCode = postalCode
        self.isoCountry = isoCountry
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case phoneNumber = "phone_number"
        case postalCode = "postal_code"
        case isoCountry = "iso_country"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encode(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(postalCode, forKey: .postalCode)
        try container.encodeIfPresent(isoCountry, forKey: .isoCountry)
    }
}

