//
// SynthesizerCost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SynthesizerCost: Codable, JSONEncodable, Hashable {

    /** The provider of the synthetizer. */
    public var provider: WakoApiModelsSynthesizerProvider
    /** The cost for the synthetizer usage. Returns zero, if the provider account you provided was used. */
    public var cost: Double
    /** The number of characters used for the synthetizer. */
    public var characters: Int
    /** Whether the provider account you provided was used. If true, the cost will be zero. */
    public var external: Bool

    public init(provider: WakoApiModelsSynthesizerProvider, cost: Double, characters: Int, external: Bool) {
        self.provider = provider
        self.cost = cost
        self.characters = characters
        self.external = external
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case cost
        case characters
        case external
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(cost, forKey: .cost)
        try container.encode(characters, forKey: .characters)
        try container.encode(external, forKey: .external)
    }
}

