//
// TelephonyCost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TelephonyCost: Codable, JSONEncodable, Hashable {

    /** The provider of the phone number used. */
    public var provider: WakoApiModelsPhoneNumberProvider
    /** The cost for the telephony usage. Returns zero, if the phone number was imported. */
    public var cost: Double
    /** The number of minutes used for the telephony. */
    public var seconds: Double
    /** Whether the phone number was imported. If true, the cost will be zero. */
    public var external: Bool

    public init(provider: WakoApiModelsPhoneNumberProvider, cost: Double, seconds: Double, external: Bool) {
        self.provider = provider
        self.cost = cost
        self.seconds = seconds
        self.external = external
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case cost
        case seconds
        case external
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(cost, forKey: .cost)
        try container.encode(seconds, forKey: .seconds)
        try container.encode(external, forKey: .external)
    }
}

