//
// Transcriber.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Transcriber: Codable, JSONEncodable, Hashable {

    public enum Provider: AnyCodable, Codable, JSONEncodable, CaseIterable {
        case azure = azure
    }
    /** The transcriber provider. */
    public var provider: Provider? = .azure
    /** The deepgram model to use. */
    public var model: DeepgramModel?
    /** The selected language for the transcription. */
    public var language: DeepgramLanguages?
    /** Specific keywords you want to detect in the transcription. This is usefull to correctly understand product or company names. */
    public var keywords: AnyCodable?
    /** The selected languages for the transcription. */
    public var languages: AnyCodable?

    public init(provider: Provider? = .azure, model: DeepgramModel? = nil, language: DeepgramLanguages? = nil, keywords: AnyCodable? = nil, languages: AnyCodable? = nil) {
        self.provider = provider
        self.model = model
        self.language = language
        self.keywords = keywords
        self.languages = languages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case model
        case language
        case keywords
        case languages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(model, forKey: .model)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(keywords, forKey: .keywords)
        try container.encodeIfPresent(languages, forKey: .languages)
    }
}

