//
// WakoApiModelsTranscriberProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum WakoApiModelsTranscriberProvider: String, Codable, CaseIterable {
    case deepgram = "deepgram"
    case azure = "azure"
}
