//
// WakoApiModelsSynthesizerProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum WakoApiModelsSynthesizerProvider: String, Codable, CaseIterable {
    case azure = "azure"
    case elevenlabs = "elevenlabs"
    case rime = "rime"
}
