//
// WakoApiModelsLanguageModelProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An enumeration. */
public enum WakoApiModelsLanguageModelProvider: String, Codable, CaseIterable {
    case openai = "openai"
}
